// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type ComicsDocumentDataSlicesSlice = ComicSlice;

/**
 * Content for comics documents
 */
interface ComicsDocumentData {
  /**
   * Slice Zone field in *comics*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: comics.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ComicsDocumentDataSlicesSlice>; /**
   * Meta Title field in *comics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: comics.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *comics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: comics.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *comics*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: comics.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * comics document from Prismic
 *
 * - **API ID**: `comics`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ComicsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ComicsDocumentData>,
    "comics",
    Lang
  >;

type FinsterkammerDocumentDataSlicesSlice =
  | YoutubeVideoPlaylistSlice
  | YoutubeVideoSlice;

/**
 * Content for finsterKammer documents
 */
interface FinsterkammerDocumentData {
  /**
   * Slice Zone field in *finsterKammer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: finsterkammer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FinsterkammerDocumentDataSlicesSlice>; /**
   * Meta Title field in *finsterKammer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: finsterkammer.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *finsterKammer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: finsterkammer.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *finsterKammer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: finsterkammer.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * finsterKammer document from Prismic
 *
 * - **API ID**: `finsterkammer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FinsterkammerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FinsterkammerDocumentData>,
    "finsterkammer",
    Lang
  >;

/**
 * Item in *footer → social Media*
 */
export interface FooterDocumentDataSocialMediaItem {
  /**
   * link field in *footer → social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *footer → weitere Links*
 */
export interface FooterDocumentDataOtherLinksItem {
  /**
   * link field in *footer → weitere Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.other_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * social Media field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_media: prismic.GroupField<Simplify<FooterDocumentDataSocialMediaItem>>;

  /**
   * weitere Links field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.other_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  other_links: prismic.GroupField<Simplify<FooterDocumentDataOtherLinksItem>>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *header → Navigation*
 */
export interface HeaderDocumentDataNavigationItem {
  /**
   * link field in *header → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for header documents
 */
interface HeaderDocumentData {
  /**
   * Seiten Title field in *header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Logo field in *header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation field in *header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<HeaderDocumentDataNavigationItem>>;
}

/**
 * header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice = BlogpostsSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Figure field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.figure
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  figure: prismic.ImageField<never>;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type IllustrationsDocumentDataSlicesSlice = GallerySlice;

/**
 * Content for illustrations documents
 */
interface IllustrationsDocumentData {
  /**
   * Slice Zone field in *illustrations*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: illustrations.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<IllustrationsDocumentDataSlicesSlice>; /**
   * Meta Title field in *illustrations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: illustrations.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *illustrations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: illustrations.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *illustrations*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: illustrations.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * illustrations document from Prismic
 *
 * - **API ID**: `illustrations`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IllustrationsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<IllustrationsDocumentData>,
    "illustrations",
    Lang
  >;

type PlainTextDocumentDataSlicesSlice = TextSlice;

/**
 * Content for plain Text documents
 */
interface PlainTextDocumentData {
  /**
   * Slice Zone field in *plain Text*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: plain_text.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PlainTextDocumentDataSlicesSlice>; /**
   * Meta Title field in *plain Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: plain_text.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *plain Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: plain_text.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *plain Text*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: plain_text.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * plain Text document from Prismic
 *
 * - **API ID**: `plain_text`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PlainTextDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PlainTextDocumentData>,
    "plain_text",
    Lang
  >;

/**
 * Item in *settings → Hintergrund*
 */
export interface SettingsDocumentDataBackgroundItem {
  /**
   * Bild field in *settings → Hintergrund*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.background[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * Hintergrund field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.background[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  background: prismic.GroupField<Simplify<SettingsDocumentDataBackgroundItem>>;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type SpeakerDocumentDataSlicesSlice = AudioSlice | YoutubeVideoSlice;

/**
 * Content for Speaker documents
 */
interface SpeakerDocumentData {
  /**
   * Slice Zone field in *Speaker*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SpeakerDocumentDataSlicesSlice>; /**
   * Meta Title field in *Speaker*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: speaker.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Speaker*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: speaker.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Speaker*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Speaker document from Prismic
 *
 * - **API ID**: `speaker`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SpeakerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SpeakerDocumentData>,
    "speaker",
    Lang
  >;

export type AllDocumentTypes =
  | ComicsDocument
  | FinsterkammerDocument
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | IllustrationsDocument
  | PlainTextDocument
  | SettingsDocument
  | SpeakerDocument;

/**
 * Primary content in *Audio → Default → Primary*
 */
export interface AudioSliceDefaultPrimary {
  /**
   * sound field in *Audio → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: audio.default.primary.sound
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  sound: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * optional text field in *Audio → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audio.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Audio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AudioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AudioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Audio*
 */
type AudioSliceVariation = AudioSliceDefault;

/**
 * Audio Shared Slice
 *
 * - **API ID**: `audio`
 * - **Description**: Audio
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AudioSlice = prismic.SharedSlice<"audio", AudioSliceVariation>;

/**
 * Item in *Blogposts → Default → Primary → Posts*
 */
export interface BlogpostsSliceDefaultPrimaryPostsItem {
  /**
   * Titel field in *Blogposts → Default → Primary → Posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.default.primary.posts[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Datum field in *Blogposts → Default → Primary → Posts*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.default.primary.posts[].date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Post field in *Blogposts → Default → Primary → Posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.default.primary.posts[].post
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  post: prismic.RichTextField;
}

/**
 * Primary content in *Blogposts → Default → Primary*
 */
export interface BlogpostsSliceDefaultPrimary {
  /**
   * Posts field in *Blogposts → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.default.primary.posts[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  posts: prismic.GroupField<Simplify<BlogpostsSliceDefaultPrimaryPostsItem>>;
}

/**
 * Default variation for Blogposts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogpostsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogpostsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blogposts*
 */
type BlogpostsSliceVariation = BlogpostsSliceDefault;

/**
 * Blogposts Shared Slice
 *
 * - **API ID**: `blogposts`
 * - **Description**: Blogposts
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogpostsSlice = prismic.SharedSlice<
  "blogposts",
  BlogpostsSliceVariation
>;

/**
 * Item in *Comic → Default → Primary → comics*
 */
export interface ComicSliceDefaultPrimaryComicsItem {
  /**
   * title field in *Comic → Default → Primary → comics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comic.default.primary.comics[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * slides field in *Comic → Default → Primary → comics*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: comic.default.primary.comics[].slides
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  slides: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *Comic → Default → Primary*
 */
export interface ComicSliceDefaultPrimary {
  /**
   * comics field in *Comic → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: comic.default.primary.comics[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  comics: prismic.GroupField<Simplify<ComicSliceDefaultPrimaryComicsItem>>;
}

/**
 * Default variation for Comic Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComicSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ComicSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Comic*
 */
type ComicSliceVariation = ComicSliceDefault;

/**
 * Comic Shared Slice
 *
 * - **API ID**: `comic`
 * - **Description**: Comic
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComicSlice = prismic.SharedSlice<"comic", ComicSliceVariation>;

/**
 * Item in *Gallery → Default → Primary → pictures*
 */
export interface GallerySliceDefaultPrimaryPicturesItem {
  /**
   * picture field in *Gallery → Default → Primary → pictures*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.pictures[].picture
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  picture: prismic.ImageField<never>;
}

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * pictures field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.pictures[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  pictures: prismic.GroupField<
    Simplify<GallerySliceDefaultPrimaryPicturesItem>
  >;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Item in *SingleYoutubeVideo → Default → Primary → videos*
 */
export interface YoutubeVideoSliceDefaultPrimaryVideosItem {
  /**
   * Optionaler Titel field in *SingleYoutubeVideo → Default → Primary → videos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: youtube_video.default.primary.videos[].titel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titel: prismic.KeyTextField;

  /**
   * video field in *SingleYoutubeVideo → Default → Primary → videos*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: youtube_video.default.primary.videos[].video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video: prismic.EmbedField;

  /**
   * Optionaler Text field in *SingleYoutubeVideo → Default → Primary → videos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: youtube_video.default.primary.videos[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *SingleYoutubeVideo → Default → Primary*
 */
export interface YoutubeVideoSliceDefaultPrimary {
  /**
   * videos field in *SingleYoutubeVideo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: youtube_video.default.primary.videos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  videos: prismic.GroupField<
    Simplify<YoutubeVideoSliceDefaultPrimaryVideosItem>
  >;
}

/**
 * Default variation for SingleYoutubeVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type YoutubeVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<YoutubeVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SingleYoutubeVideo*
 */
type YoutubeVideoSliceVariation = YoutubeVideoSliceDefault;

/**
 * SingleYoutubeVideo Shared Slice
 *
 * - **API ID**: `youtube_video`
 * - **Description**: YoutubeVideo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type YoutubeVideoSlice = prismic.SharedSlice<
  "youtube_video",
  YoutubeVideoSliceVariation
>;

/**
 * Item in *YoutubeVideoPlaylist → Default → Primary → Playlist*
 */
export interface YoutubeVideoPlaylistSliceDefaultPrimaryPlaylistItem {
  /**
   * video field in *YoutubeVideoPlaylist → Default → Primary → Playlist*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: youtube_video_playlist.default.primary.playlist[].video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video: prismic.EmbedField;
}

/**
 * Primary content in *YoutubeVideoPlaylist → Default → Primary*
 */
export interface YoutubeVideoPlaylistSliceDefaultPrimary {
  /**
   * Optional Titel field in *YoutubeVideoPlaylist → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: youtube_video_playlist.default.primary.optionalTitel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  optionalTitel: prismic.KeyTextField;

  /**
   * Playlist field in *YoutubeVideoPlaylist → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: youtube_video_playlist.default.primary.playlist[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  playlist: prismic.GroupField<
    Simplify<YoutubeVideoPlaylistSliceDefaultPrimaryPlaylistItem>
  >;
}

/**
 * Default variation for YoutubeVideoPlaylist Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type YoutubeVideoPlaylistSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<YoutubeVideoPlaylistSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *YoutubeVideoPlaylist*
 */
type YoutubeVideoPlaylistSliceVariation = YoutubeVideoPlaylistSliceDefault;

/**
 * YoutubeVideoPlaylist Shared Slice
 *
 * - **API ID**: `youtube_video_playlist`
 * - **Description**: YoutubeVideoPlaylist
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type YoutubeVideoPlaylistSlice = prismic.SharedSlice<
  "youtube_video_playlist",
  YoutubeVideoPlaylistSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ComicsDocument,
      ComicsDocumentData,
      ComicsDocumentDataSlicesSlice,
      FinsterkammerDocument,
      FinsterkammerDocumentData,
      FinsterkammerDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialMediaItem,
      FooterDocumentDataOtherLinksItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      IllustrationsDocument,
      IllustrationsDocumentData,
      IllustrationsDocumentDataSlicesSlice,
      PlainTextDocument,
      PlainTextDocumentData,
      PlainTextDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataBackgroundItem,
      SpeakerDocument,
      SpeakerDocumentData,
      SpeakerDocumentDataSlicesSlice,
      AllDocumentTypes,
      AudioSlice,
      AudioSliceDefaultPrimary,
      AudioSliceVariation,
      AudioSliceDefault,
      BlogpostsSlice,
      BlogpostsSliceDefaultPrimaryPostsItem,
      BlogpostsSliceDefaultPrimary,
      BlogpostsSliceVariation,
      BlogpostsSliceDefault,
      ComicSlice,
      ComicSliceDefaultPrimaryComicsItem,
      ComicSliceDefaultPrimary,
      ComicSliceVariation,
      ComicSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimaryPicturesItem,
      GallerySliceDefaultPrimary,
      GallerySliceVariation,
      GallerySliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault,
      YoutubeVideoSlice,
      YoutubeVideoSliceDefaultPrimaryVideosItem,
      YoutubeVideoSliceDefaultPrimary,
      YoutubeVideoSliceVariation,
      YoutubeVideoSliceDefault,
      YoutubeVideoPlaylistSlice,
      YoutubeVideoPlaylistSliceDefaultPrimaryPlaylistItem,
      YoutubeVideoPlaylistSliceDefaultPrimary,
      YoutubeVideoPlaylistSliceVariation,
      YoutubeVideoPlaylistSliceDefault,
    };
  }
}
