// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  audio: defineAsyncComponent(() => import("./Audio/index.vue")),
  blogposts: defineAsyncComponent(() => import("./Blogposts/index.vue")),
  comic: defineAsyncComponent(() => import("./Comic/index.vue")),
  gallery: defineAsyncComponent(() => import("./Gallery/index.vue")),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
  youtube_video: defineAsyncComponent(
    () => import("./SingleYoutubeVideo/index.vue"),
  ),
  youtube_video_playlist: defineAsyncComponent(
    () => import("./YoutubeVideoPlaylist/index.vue"),
  ),
});
